apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-gitops
placementRef:
  name: placement-policy-gitops
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: policy-managed-gitops-operator
    kind: Policy
    apiGroup: policy.open-cluster-management.io
  - name: policy-sealed-secrets-seed
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-gitops
spec:
  clusterConditions:
    - status: "True"
      type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - { key: gitops, operator: In, values: ["true"] }